### ISSUE TITLE
Installation Issue (missing file)

### ISSUE THREAD

**Issue by Navidkalantari** [anl-polaris/polaris#1]
Hi, 
I'm trying to compile Polaris but I'm running into different issues. After downloading the files and dependencies from Github I ran the build and configure batch file but nothing really happened. I tried using the polaris.sln file but I can't locate it. It seems to be missing. Could you please provide me with the more detail information on how to install Polaris and the sln file?
Thanks

**Comment by rweimeranl** [comment]
I need a little more information from you:
Did you build the dependencies without any errors (using the get_deps.cmd file as in the instructions)?
Did you tell the configure batch file where the 3rd party libraries/headers are located (as per the instructions)?
What was the output of the configure script? It will call cmake with the 3rd party location to generate the sln file. If it can't locate the 3rd party stuff it will fail (and give the error in the command shell).
Also let me know what version of cmake you have installed, as well as the version of Visual Studio.
Are you sure you can call the C++ compiler from a command line?

**Comment by Navidkalantari** [comment]
It seems to be an issue in the MSVC. I attached the logfile of the
boost_build and gtest_build the version I have on my system is 2017 and the
cmake version is 3.12.4.
I downloaded the polarisdep folder and ran the  get_deps.cmd by specifying
its folder.

**Comment by rweimeranl** [comment]
We do not currently support MSVC 2017. Only MSVC 2015 at this time.
