### ISSUE TITLE
Embed ODB into the source

### ISSUE THREAD

**Issue by VadimSokolov** [anl-polaris/polaris#19]
So that users do not need to install ODB and/or build on Windows machines. Copy-paste ODB source to our source tree and add makefile and test with GCC and VS compiler.

**Comment by MichaelHope** [comment]
Please use the same title for the ticket as you do for whatever branch you will be doing this in  following a convention where tickets are numbered in ascending order (i.e. G-1, G-2). This will make organizing tickets for releases considerably easier.

**Comment by MichaelHope** [comment]
At a minimum please list the branch name in the ticket, otherwise it will be impossible to match up.

**Comment by jaauld14** [comment]
New install scripts obviate the need for this.  Will keep separate for now.
