### ISSUE TITLE
C-2 Treat short links in capacity based model

### ISSUE THREAD

**Issue by VadimSokolov** [anl-polaris/polaris#35]
So we can handle transition to a short link, we need to be able to move car JA->JA
move addCar function from TravelinArea to Road class, so the usage is:
state = targetRoad->addCar(this);

See example in 
MoveResult Car::leaveRoad(double dt) (Car.cpp)

**Comment by jaauld14** [comment]
DEPRECATED - NO ONE IS WORKING ON THIS BRANCH
