### ISSUE TITLE
IO-1: Refactor Data Tables

### ISSUE THREAD

**Issue by VadimSokolov** [anl-polaris/polaris#38]
We need to clean the tables used:
-  Remove transit tables (fare, line, schedule, driver, Route_Nodes,Ridership)
- Remove ITS tables (LinkList, Component, VMS, Fixed_Sensor, HAR, VSS, Depot, OpenShoulder, Action, Action_Key, Microsoft_Event)
- Add Path table to demand database (id, link, dir, seq, arrival_time, departure_time)

**Comment by jaauld14** [comment]
Path has been added to demand table. Most ITS tables removed (retaind VMS, HAR, VSS). Transit tables removed pending new Transit DB design

Commit date 05/23/17
