### ISSUE TITLE
typo in polarisdeps/get-deps.cmd

### ISSUE THREAD

**Issue by mjavanmardi** [anl-polaris/polaris#61]
In the following line, "rapisjson_build" should be changed by "rapidjson_build"
IF EXIST %LOGDIR%\rapidjson_build.log (DEL %LOGDIR%\rapisjson_build.log)

**Comment by jaauld14** [comment]
Fixed in master commit: https://github.com/anl-polaris/polaris/commit/c3c869eef970a65b8cfb55b00cf829982df1c0df
