### ISSUE TITLE
Type mismatch?

### ISSUE THREAD

**Issue by gkmurthy10** [anl-polaris/polaris#65]
https://github.com/anl-polaris/polaris/blob/9f9ba416ee6535772e56b92f9f29c99f502da1e8/libs/traffic_simulator/Zone_Implementation.h#L163

Should this be activity_location_type? Cause there's a vector of links a few lines below.

https://github.com/anl-polaris/polaris/blob/9f9ba416ee6535772e56b92f9f29c99f502da1e8/libs/traffic_simulator/Zone_Implementation.h#L175

**Comment by jaauld14** [comment]
Good catch...this should be activity_location_type - fortunately this didn't cause any error in running due to the implicit pointer casting. I will make this fix...
